### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [AndrieiGensh/Python_SpaceInvaders#3]
1. [Nie używać skrótów](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L11) (2. rozdział Poradnika). To samo z `print_mes()`, `test_sur` , `rect`, [`en`](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L743) itp.
2. [Używać slashów zamiast backslashów w ścieżkach plików](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L62) (3. rozdział).
3. [Tu](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L36) lepiej użyć `super()`. To samo wszędzie.
4. [W takich miejscach](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L152) astosować przepis `Assets` z 3. rozdziału, dzięki czemu tworzenie każdego obiektu nie będzie powodowało odczytu z dysku.
5. [Tak](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L296) się pisało w Pythonie 2. W Pythonie 3 wystarczy `super()`.
6. [To](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L65) zbędne.
7. Magiczne stałe do `direction`: 1 i -1 nazwać (2. rozdział), np. `UP` i `DOWN`.
8. [Usunąć takie puste wiersze, które tylko przeszkadzają w czytaniu](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L807).
9. [Unikać backlashów](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/Space_invaders.py#L818) (2. rozdział). Zamiast nich otoczyć warunek nawiasami.
10. Przemianować `test_space_invaders.py` na `Space_invaders_test.py` (3. rozdział).
11. [To](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/test_space_invaders.py#L30) rozbić na dwie asercje. [To](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/test_space_invaders.py#L50) tak samo.
12. [To](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/c74774384b8d69c39e47dbfc2e3505e9c2f590f3/test_space_invaders.py#L7) niepotrzebne i szkodliwe. Zamiast tego użyć metody `setUp(self)`.
13. Testów jest trochę mało. Przydałaby się jeszcze jedna metoda (w testach do tej samej klasy albo do innej).

**Comment by MarcinCiura** [comment]
1. Proszę nie zamykać tego *Issue*, dopóki nie skończymy.
2. Proszę odpowiadać tutaj, a nie emaiem.
3. Oczywiście, że da się zmienić `rect` na `rectangle` w Pańskim kodzie (nie w wywołanich `pygame`). Proszę dokonać zmian i jeśli znowu pojawi się błąd, wgrać zmieniony kod na github (w innej gałęzi niż `master`) i skopiować tu cały komunikat o błędzie.

**Comment by AndrieiGensh** [comment]
Szanowny Panie Doktorze,
zmieniony kod umieściłem w gałęzi "issue" (https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/issue/Space_invaders.py). 
Przy uruchomieniu programu dostaję taki komunikat:

Traceback (most recent call last):
  File "C:/Users/user/Desktop/Python_my/Space_invaders.py", line 848, in <module>
    main()
  File "C:/Users/user/Desktop/Python_my/Space_invaders.py", line 841, in main
    game_instance.run_game()
  File "C:/Users/user/Desktop/Python_my/Space_invaders.py", line 806, in run_game
    self.collisions()
  File "C:/Users/user/Desktop/Python_my/Space_invaders.py", line 743, in collisions
    for enemy in pygame.sprite.groupcollide(self.enemies,
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\pygame\sprite.py", line 1566, in groupcollide
    c = SC(s, groupb, dokillb, collided)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\pygame\sprite.py", line 1523, in spritecollide
    spritecollide = sprite.rect.colliderect
AttributeError: 'Enemy' object has no attribute 'rect'

Przeczytałem dokumentację do funkcji groupcollide() oraz spritecollide(). Poprawne działanie tych funkcji (bez tworzenia własnej funkcji do wyznaczenia, czy dwa obiekty typu "Sprite" kolidują) wymaga definiowania w klasie dziedziczących po Sprite pola o nazwie "rect".  To samo dotyczy metody draw() i innych podobnych metod z modułu pygame.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. Projekt wygląda całkiem porządnie. Po uwzględnieniu poniższych uwag będę mógł go zaliczyć.
1. Proszę swoje odkrycia nt. pola `rect` umieścić w komentarzu w odpowiednim miejscu kodu.
2. [Te docstringi wyrzucić; są zupełnie zbędne](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/cdb0406985855342affb6d0a971d5e752f67a228/Space_invaders.py#L1). [Te też](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/cdb0406985855342affb6d0a971d5e752f67a228/Space_invaders_test.py#L11) (3. rozdział Poradnika).
3. [Zbędny wiersz](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/cdb0406985855342affb6d0a971d5e752f67a228/Space_invaders_test.py#L14).
4. [`.assertIsNone()`](https://github.com/AndrieiGensh/Python_SpaceInvaders/blob/cdb0406985855342affb6d0a971d5e752f67a228/Space_invaders_test.py#L32).
5. Dopisać dwa magiczne wiersze na końcu testów.

**Comment by AndrieiGensh** [comment]
Szanowny Panie Doktorze,
uwzględniłem powyższe uwagi i umieściłem zmieniony kod w gałęzi "master" (https://github.com/AndrieiGensh/Python_SpaceInvaders/tree/master).

**Comment by MarcinCiura** [comment]
LGTM
